name: Publish
on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@fsouza"

      - run: yarn install --frozen-lockfile

      - run: npm publish --access public
